### ISSUE TITLE
 Could not load file or assembly 'GreyMagic.dll' or one of its dependencies

### ISSUE THREAD

**Issue by 0Melon0** [lesuixin/Hearthstone-Hearthbuddy#14]
运行 TS正式版时 报错 请问各位大大要怎么解决

```
OS Name: Microsoft Windows 10 家庭版
OS Version: 10.0.19043
OS Architecture: 64 位
InstalledUICulture: zh-CN [Chinese (Simplified, China)]
CurrentUICulture: zh-CN [Chinese (Simplified, China)]
CurrentCulture: zh-CN [Chinese (Simplified, China)]

2021-08-17 14:57:03,377 [1] INFO  CustomLogger (null) - 现在设置JitProfiles...
2021-08-17 14:57:03,377 [1] INFO  CustomLogger (null) - JitProfiles 设置成功!
2021-08-17 14:57:03,377 [1] INFO  CustomLogger (null) - 现在开始预启动任务.
2021-08-17 14:57:03,377 [1] INFO  CustomLogger (null) - 现在检查先决条件...
2021-08-17 14:57:03,408 [1] ERROR CustomLogger (null) - [添加调试] 执行时出错：
System.IO.FileNotFoundException: Could not load file or assembly 'GreyMagic.dll' or one of its dependencies. 找不到指定的模块。
File name: 'GreyMagic.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at (App )


2021-08-17 14:57:03,408 [1] ERROR CustomLogger (null) - System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at (App )
   at Hearthbuddy.App.method_0()
   at (App , StartupEventArgs )
2021-08-17 14:57:03,611 [1] INFO  CustomLogger (null) - [AuthRegion] China.
```

**Comment by Heryoare** [comment]
同样的情况 请问解决了么

**Comment by LUERUI** [comment]
我也是这样，解决了吗？

**Comment by xiao-huangren** [comment]
同问
